openapi: 3.0.3
info:
  title: Solution API
  version: 1.0.0
  description: Your project description
paths:
  /solution-api:
    get:
      operationId: solution_api_retrieve
      tags:
      - solution-api
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /solution-api/business-account:
    get:
      operationId: solution_api_business_account_retrieve
      description: |-
        A simple view to create and edit business accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAccount'
          description: ''
    post:
      operationId: solution_api_business_account_create
      description: |-
        A simple view to create and edit business accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessAccount'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BusinessAccount'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BusinessAccount'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAccount'
          description: ''
    put:
      operationId: solution_api_business_account_update
      description: |-
        A simple view to create and edit business accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BusinessAccount'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BusinessAccount'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BusinessAccount'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAccount'
          description: ''
    patch:
      operationId: solution_api_business_account_partial_update
      description: |-
        A simple view to create and edit business accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBusinessAccount'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBusinessAccount'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBusinessAccount'
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessAccount'
          description: ''
    delete:
      operationId: solution_api_business_account_destroy
      description: |-
        A simple view to create and edit business accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /solution-api/change-password:
    patch:
      operationId: solution_api_change_password_partial_update
      tags:
      - solution-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedChangePassword'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedChangePassword'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedChangePassword'
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChangePassword'
          description: ''
  /solution-api/job-data:
    get:
      operationId: solution_api_job_data_retrieve
      tags:
      - solution-api
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /solution-api/personal-account:
    get:
      operationId: solution_api_personal_account_retrieve
      description: |-
        A simple view to create and edit personal accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalAccount'
          description: ''
    post:
      operationId: solution_api_personal_account_create
      description: |-
        A simple view to create and edit personal accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalAccount'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PersonalAccount'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PersonalAccount'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalAccount'
          description: ''
    put:
      operationId: solution_api_personal_account_update
      description: |-
        A simple view to create and edit personal accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonalAccount'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PersonalAccount'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PersonalAccount'
        required: true
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalAccount'
          description: ''
    patch:
      operationId: solution_api_personal_account_partial_update
      description: |-
        A simple view to create and edit personal accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPersonalAccount'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPersonalAccount'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPersonalAccount'
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalAccount'
          description: ''
    delete:
      operationId: solution_api_personal_account_destroy
      description: |-
        A simple view to create and edit personal accounts
        Required fields:
            role
            name
            location
      tags:
      - solution-api
      security:
      - basicAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /solution-api/roles:
    get:
      operationId: solution_api_roles_retrieve
      tags:
      - solution-api
      security:
      - basicAuth: []
      - cookieAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  schemas:
    BusinessAccount:
      type: object
      properties:
        logo:
          type: string
          format: uri
        company_name:
          type: string
          maxLength: 50
        address:
          type: string
          maxLength: 255
        legal_name:
          type: string
          maxLength: 100
        industry:
          type: string
          maxLength: 50
        company_size:
          $ref: '#/components/schemas/CompanySizeEnum'
        location:
          type: string
          maxLength: 50
        company_url:
          type: string
          format: uri
          maxLength: 200
        description:
          type: string
        personal_photo:
          type: string
          format: uri
        role:
          type: string
          maxLength: 50
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        phone:
          type: string
          pattern: ^(\d{1,3})(\d{2})(\d{9})$
          maxLength: 20
        verified_id:
          type: boolean
        last_update:
          type: string
          format: date-time
          readOnly: true
      required:
      - address
      - company_name
      - company_size
      - first_name
      - industry
      - last_name
      - last_update
      - legal_name
      - location
      - phone
      - role
    ChangePassword:
      type: object
      description: |-
        This regular expression breaks down as follows:
        ^: Start of the string.
        (?=.*[A-Z]): Lookahead assertion to ensure at least one uppercase letter.
        (?=.*\d): Lookahead assertion to ensure at least one digit (number).
        (?=.*[@#$%^&+=!]): Lookahead assertion to ensure at least one special character. You can add more special characters inside the square brackets if needed.
        .{8,20}: Match any character (except for a newline) between 8 and 20 times.
        $: End of the string.
      properties:
        old_password:
          type: string
          maxLength: 20
        new_password:
          type: string
          pattern: ^(?=.*[A-Z])(?=.*\d)(?=.*[@#$%^&+=!]).{8,20}$
        new_password_confirmation:
          type: string
          pattern: ^(?=.*[A-Z])(?=.*\d)(?=.*[@#$%^&+=!]).{8,20}$
      required:
      - new_password
      - new_password_confirmation
      - old_password
    CompanySizeEnum:
      enum:
      - 0
      - 1
      - 2
      - 3
      - 4
      type: integer
      description: |-
        * `0` - Fewer than 10 employees
        * `1` - 10 to 50 employees
        * `2` - 50 to 250 employees
        * `3` - 250 to 500 employees
        * `4` - More than 500 employees
    PatchedBusinessAccount:
      type: object
      properties:
        logo:
          type: string
          format: uri
        company_name:
          type: string
          maxLength: 50
        address:
          type: string
          maxLength: 255
        legal_name:
          type: string
          maxLength: 100
        industry:
          type: string
          maxLength: 50
        company_size:
          $ref: '#/components/schemas/CompanySizeEnum'
        location:
          type: string
          maxLength: 50
        company_url:
          type: string
          format: uri
          maxLength: 200
        description:
          type: string
        personal_photo:
          type: string
          format: uri
        role:
          type: string
          maxLength: 50
        first_name:
          type: string
          maxLength: 50
        last_name:
          type: string
          maxLength: 50
        phone:
          type: string
          pattern: ^(\d{1,3})(\d{2})(\d{9})$
          maxLength: 20
        verified_id:
          type: boolean
        last_update:
          type: string
          format: date-time
          readOnly: true
    PatchedChangePassword:
      type: object
      description: |-
        This regular expression breaks down as follows:
        ^: Start of the string.
        (?=.*[A-Z]): Lookahead assertion to ensure at least one uppercase letter.
        (?=.*\d): Lookahead assertion to ensure at least one digit (number).
        (?=.*[@#$%^&+=!]): Lookahead assertion to ensure at least one special character. You can add more special characters inside the square brackets if needed.
        .{8,20}: Match any character (except for a newline) between 8 and 20 times.
        $: End of the string.
      properties:
        old_password:
          type: string
          maxLength: 20
        new_password:
          type: string
          pattern: ^(?=.*[A-Z])(?=.*\d)(?=.*[@#$%^&+=!]).{8,20}$
        new_password_confirmation:
          type: string
          pattern: ^(?=.*[A-Z])(?=.*\d)(?=.*[@#$%^&+=!]).{8,20}$
    PatchedPersonalAccount:
      type: object
      properties:
        profession:
          type: string
        photo:
          type: string
          format: uri
        first_name:
          type: string
          maxLength: 20
          minLength: 2
        last_name:
          type: string
          maxLength: 20
          minLength: 2
        birthdate:
          type: string
          format: date
        phone:
          type: string
          pattern: ^(\d{1,3})(\d{2})(\d{9})$
          maxLength: 20
        rating:
          type: integer
          maximum: 5
          minimum: 0
        location:
          type: string
          maxLength: 50
        about:
          type: string
          maxLength: 255
        review_count:
          type: integer
          minimum: 0
        jobs_done:
          type: integer
          minimum: 0
        verified_id:
          type: boolean
        driving_license:
          type: boolean
        last_update:
          type: string
          format: date-time
          readOnly: true
    PersonalAccount:
      type: object
      properties:
        profession:
          type: string
        photo:
          type: string
          format: uri
        first_name:
          type: string
          maxLength: 20
          minLength: 2
        last_name:
          type: string
          maxLength: 20
          minLength: 2
        birthdate:
          type: string
          format: date
        phone:
          type: string
          pattern: ^(\d{1,3})(\d{2})(\d{9})$
          maxLength: 20
        rating:
          type: integer
          maximum: 5
          minimum: 0
        location:
          type: string
          maxLength: 50
        about:
          type: string
          maxLength: 255
        review_count:
          type: integer
          minimum: 0
        jobs_done:
          type: integer
          minimum: 0
        verified_id:
          type: boolean
        driving_license:
          type: boolean
        last_update:
          type: string
          format: date-time
          readOnly: true
      required:
      - birthdate
      - first_name
      - last_name
      - last_update
      - location
      - phone
      - profession
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
