# Generated by Django 4.2.1 on 2023-06-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solution", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="businessaccount",
            old_name="enterprise_img",
            new_name="enterprise_logo",
        ),
        migrations.RenameField(
            model_name="businessaccount",
            old_name="representative_photo",
            new_name="personal_photo",
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="businessaccount",
            name="verified_id",
            field=models.BooleanField(default=False),
        ),
    ]
