# Generated by Django 4.2.2 on 2023-06-29 03:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("solution", "0002_auto_20230618_1642"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personalaccount",
            old_name="personal_photo",
            new_name="photo",
        ),
    ]
